### PR TITLE
Add simple control mods for newrelic-infra service resource

### PR DESCRIPTION
**Pull request by davehewy**
Found this a useful (and missing) addition to the codebase. Thought i'd give contributing it back a stab. Please comment.

### CODE REVIEW

**Comment by davehewy** [comment]
@craigwatson since you were the last contributor to this repo. Any chance of this being reviewed? Happy to make amendments.

**Comment by craigwatson** [comment]
HI @DaveHewy, thanks for the PR - it's definitely something I'm looking to review today, workload permitting 👍

**Comment by davehewy** [comment]
+1

**Comment by davehewy** [comment]
@craigwatson any updates?

**Comment by craigwatson** [comment]
Thanks for the PR and apologies for the delay, version 2.3.0 has now been released to the Forge! 👍

**Comment by davehewy** [comment]
@craigwatson great stuff. cheers :+1:

**Pull request merged**
